services:
  mysql:
    image: mysql:8.0
    container_name: miseprep-mysql
    env_file:
      - .env
    ports:
      - "23306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: miseprep-api
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "28080:28080"
    depends_on:
      - mysql

volumes:
  mysql-data:
