server:
  port: 28080
  forward-headers-strategy: framework

spring:
  application:
    name: miseprep-api


  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  allowed-redirect-uris:
    - ${KAKAO_REDIRECT_URI_LOCAL}
    - ${KAKAO_REDIRECT_URI_PROD}

openai:
  api-key: ${OPENAI_API_KEY}

