spring:
  application:
    name: miseprep-api
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 28080

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_EXPIRATION}
    refresh: ${JWT_REFRESH_EXPIRATION}
